name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build Release
      run: msbuild /p:Configuration=Release /p:Platform=x64

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          x64/Release/VIRUS38.exe
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: Automated build of VIRUS38
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
